import React from "react"
import { Document, Page, Text, View, StyleSheet, renderToBuffer, type DocumentProps } from "@react-pdf/renderer"
import type { AcademicEventApplication, ApplicationTypeId } from "./types"

const styles = StyleSheet.create({
  page: { padding: 40, paddingBottom: 56, fontSize: 10, fontFamily: "Helvetica", lineHeight: 1.4 },
  docTitle: { fontSize: 14, marginBottom: 4, textAlign: "center" },
  docSubtitle: { fontSize: 9, marginBottom: 14, textAlign: "center", color: "#555" },
  sectionHeading: { fontSize: 11, fontWeight: 700, marginTop: 14, marginBottom: 6 },
  articleHeading: { fontSize: 11, fontWeight: 700, marginTop: 14, marginBottom: 6 },
  clauseRow: { flexDirection: "row", marginBottom: 5 },
  clauseNum: { width: 18, fontWeight: 700 },
  clauseText: { flex: 1 },
  subBullet: { marginLeft: 22, marginBottom: 3 },
  bulletRow: { flexDirection: "row", marginBottom: 3 },
  bulletMark: { width: 10 },
  bulletText: { flex: 1 },
  paragraph: { marginBottom: 6 },
  smallLabel: { fontWeight: 700 },
  ackBox: {
    marginTop: 8,
    marginBottom: 14,
    padding: 8,
    fontSize: 8.5,
    fontStyle: "italic",
    color: "#333",
    borderWidth: 1,
    borderColor: "#ccc",
    borderStyle: "solid",
  },
  placeholderNote: {
    marginBottom: 8,
    fontSize: 9,
    fontStyle: "italic",
    color: "#8a5a00",
  },
  twoColumnRow: { flexDirection: "row", marginBottom: 8 },
  column: { flex: 1, paddingRight: 10 },
  columnHeading: { fontWeight: 700, marginBottom: 4 },
  signatureBlock: { marginTop: 18 },
  signatureLine: { marginBottom: 4 },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#777",
    textAlign: "center",
    paddingTop: 4,
    borderTopWidth: 0.5,
    borderTopColor: "#ccc",
    borderTopStyle: "solid",
  },
  letterheadOrg: { fontSize: 12, fontWeight: 700, textAlign: "center" },
  letterheadTitle: { fontSize: 11, fontWeight: 700, textAlign: "center", marginTop: 4 },
  letterheadContact: { fontSize: 8, textAlign: "center", marginTop: 4, marginBottom: 14, color: "#555" },
})

function formatDate(value: string | null): string {
  return value ? new Date(value).toLocaleString("en-IN") : "N/A"
}

function Acknowledgment({ application }: { application: AcademicEventApplication }) {
  return (
    <View style={styles.ackBox}>
      <Text>
        This application was verified by a one-time code sent to the organizer&apos;s registered contact on{" "}
        {formatDate(application.otp_verified_at)}, and approved by{" "}
        {application.reviewed_by ?? "the AMASI Hon. Secretary"} on {formatDate(application.reviewed_at)}.
      </Text>
    </View>
  )
}

function Footer({ application }: { application: AcademicEventApplication }) {
  return (
    <Text style={styles.footer} fixed>
      Generated by AMASI Membership Portal — Application ID {application.id} — Version{" "}
      {application.mou_version + 1}
    </Text>
  )
}

function BulletList({ items }: { items: string[] }) {
  return (
    <>
      {items.map((item, i) => (
        <View style={styles.bulletRow} key={i}>
          <Text style={styles.bulletMark}>{"•"}</Text>
          <Text style={styles.bulletText}>{item}</Text>
        </View>
      ))}
    </>
  )
}

// ---------------------------------------------------------------------------
// Family 1: "College of MAS" numbered-section MOU — fmas / mmas / dmas
// ---------------------------------------------------------------------------

const COLLEGE_OF_MAS_COURSE_NAMES: Record<"fmas" | "mmas" | "dmas", string> = {
  fmas: "FMAS Skill Course",
  mmas: "MMAS Skill Course",
  dmas: "DMAS Skill Course",
}

interface ClauseItem {
  text: string
  subBullets?: string[]
}

interface ClauseSection {
  heading: string
  clauses: ClauseItem[]
}

function buildCollegeOfMasSections(course: string): ClauseSection[] {
  return [
    {
      heading: "PARTIES AND AUTHORITY",
      clauses: [
        {
          text: `COLLEGE OF AMASI, hereinafter called "College of MAS" (First Party) and ORGANIZING COMMITTEE OF ${course}, called "Convenor" (Second Party), enter into this MOU.`,
        },
        {
          text: `Secretary College of MAS is the authorized signatory or a person designated by college of MAS and decision-making authority for the First Party. The Convenor of ${course} represents the Second Party.`,
        },
      ],
    },
    {
      heading: "COURSE APPROVAL AND SCHEDULING",
      clauses: [
        {
          text: "Process: MOU submission → Date availability check → Approval from Secretary College of MAS or a person designated by college of MAS → Course announcement. Convenor selects venues subject to Secretary's endorsement.",
        },
        {
          text: "Requirements: College of MAS maintains full authority over name and logo usage. All materials must display College of MAS + AMASI.",
        },
      ],
    },
    {
      heading: "DIVISION OF RESPONSIBILITIES",
      clauses: [
        {
          text: "College of MAS (Head Office):",
          subBullets: [
            "Flyer, brochure, website management, and online registration",
            "Scientific program, faculty selection, e-badge preparation",
            "OMR sheets, question papers, certificates, feedback collection",
            "Financial management and vendor payments",
          ],
        },
        {
          text: "Organizing Committee:",
          subBullets: [
            "Venue, accommodation, catering, local transport arrangements",
            "AV setup, seating, signage, endotrainer setup for examination",
            "Faculty hospitality, kit distribution, local coordination",
          ],
        },
        {
          text: "Faculty: Must be AMASI members or approved by College of MAS/AMASI. Exceptions for other specialties require prior approval.",
        },
      ],
    },
    {
      heading: "PROGRAM SUBMISSION AND COORDINATION",
      clauses: [
        {
          text: "Timeline: Convener submits detailed program (committee members, venue, logistics) 6 weeks before the event. College of MAS provides faculty details and allotment of their topic 1 month in advance.",
        },
        {
          text: "Coordination: Secretary College of MAS/AMASI approval required before scientific program execution. Continuous coordination between both parties throughout preparation.",
        },
      ],
    },
    {
      heading: "FINANCIAL MANAGEMENT",
      clauses: [
        { text: "Banking: All transactions through College of MAS accounts only. Convenor may not maintain separate accounts." },
        {
          text: "Sponsorship: Convenor may receive sponsorships but all funds must be deposited in the College of MAS account. All payments will be processed through College of MAS. Sponsorship must cover any additional amount for example course dinner.",
        },
        {
          text: "Advance Payments: For hotels/catering, Convenor submits quotations and receives up to 75% advance. Balance paid after service completion. All the payments will be made directly to the vendor only.",
        },
        {
          text: "Documentation: Bills above Rs.50/- required. Bills above Rs.30,000/- require Company PAN or 20% TDS deduction. College of MAS handles verification and direct vendor payments.",
        },
        {
          text: "Registration: Managed through College of MAS website. Dashboard access provided to Convenor for real-time monitoring of participants and payments.",
        },
      ],
    },
    {
      heading: "ACADEMIC STANDARDS",
      clauses: [
        { text: "Curriculum: Scientific program standardized by College of MAS. No content changes without approval." },
        { text: "Examination: College of MAS prepares OMR sheets/question papers. Convenor sets up endo trainers." },
      ],
    },
    {
      heading: "REPORTING AND COMPLIANCE",
      clauses: [
        {
          text: "Post-Event: Convenor submits a comprehensive report with photographs within 15 days. All materials must display College of MAS and AMASI logos.",
        },
        { text: "Restrictions: No promotion of other organizations without permission. No personal/political propaganda permitted." },
        { text: "Other academic Association can be co organiser only after approval from Head office." },
      ],
    },
    {
      heading: "CANCELLATION AND SIGNATURES",
      clauses: [{ text: "Deadline: MOU must be signed at least 30 days before the event, or automatic cancellation applies." }],
    },
  ]
}

function CollegeOfMasSection({ section }: { section: ClauseSection }) {
  return (
    <View>
      <Text style={styles.sectionHeading}>{section.heading}</Text>
      {section.clauses.map((clause, i) => (
        <View key={i}>
          <View style={styles.clauseRow}>
            <Text style={styles.clauseNum}>{i + 1}.</Text>
            <Text style={styles.clauseText}>{clause.text}</Text>
          </View>
          {clause.subBullets?.map((sub, j) => (
            <View style={styles.bulletRow} key={j}>
              <Text style={[styles.bulletMark, styles.subBullet]}>{"–"}</Text>
              <Text style={styles.bulletText}>{sub}</Text>
            </View>
          ))}
        </View>
      ))}
    </View>
  )
}

function renderCollegeOfMasMou(application: AcademicEventApplication, typeLabel: string) {
  const typeId = application.application_type_id as "fmas" | "mmas" | "dmas"
  const course = COLLEGE_OF_MAS_COURSE_NAMES[typeId] ?? typeLabel
  const sections = buildCollegeOfMasSections(course)

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.docTitle}>MEMORANDUM OF UNDERSTANDING FOR {course}</Text>
        <Text style={styles.docSubtitle}>
          Headquarters: GEM Hospital, 45-A, Pankaja Mill Road, Ramanathapuram, Coimbatore - 641 045
        </Text>

        <Acknowledgment application={application} />

        {sections.map((section, i) => (
          <CollegeOfMasSection section={section} key={i} />
        ))}

        <View style={styles.signatureBlock}>
          <Text style={styles.signatureLine}>First Party: Secretary College of MAS</Text>
          <Text style={styles.signatureLine}>
            Second Party: {application.organizer_name} (Convenor, {course})
          </Text>
        </View>

        <Text style={styles.sectionHeading}>Billing / Sponsorship Account</Text>
        <Text style={styles.paragraph}>
          Bill To: College of AMASI, Address: 45 A Pankaja Mill Road, Ramanathapuram, Coimbatore, TN (33) 641045,
          IN. GSTIN: 33AABTC9091L1ZF
        </Text>
        <Text style={styles.paragraph}>
          Sponsorship Payment: Account Name: College of AMASI, Bank Name: AXIS Bank, Branch Name: TRICHY ROAD
          BRANCH, Account Number: 916020034964055, IFSC Code: UTIB000047
        </Text>

        <Footer application={application} />
      </Page>
    </Document>
  )
}

// ---------------------------------------------------------------------------
// Family 2: "Article" MOU — slcp / nextgen / meet_the_master / zonal_event
// ---------------------------------------------------------------------------

interface ArticleVars {
  programTitle: string
  programTagline: string
  purposeDetail: string
  structureBullets: string[]
  party1Responsibilities: string[]
  party2Responsibilities: string[]
  registrationFees: string[]
  sponsorshipNote: string
  facultyTerms: string[]
  eligibilityTerms: string[]
  eventNoun: string
  party2Label: string
  placeholderNote?: string
}

const SLCP_PARTY1_RESPONSIBILITIES = [
  "Provide curriculum guidance and quality standards",
  "Handle all participant certifications",
  "Designate qualified faculty members",
  "Receive ₹500 per registration from organizer",
  "Provide academic material for use in the program",
  "Maintain professional standards",
  "Provide program endorsement and branding",
]

const SLCP_PARTY2_RESPONSIBILITIES = [
  "Provide venue and facilities meeting AMASI standards",
  "Arrange faculty travel and accommodation",
  "May propose faculties which must be finalized by AMASI headquarters",
  "Will not divert from academic content without prior permission from National Director, AMASI Safe Lap Chole Program",
  "Handle logistics and participant management",
  "Submit report within 15 days",
  "Display College of MAS and AMASI logos",
  "Pay ₹500 per registration to AMASI",
  "Expenses to be borne by organizers or from sponsorship funds",
]

const SLCP_ELIGIBILITY_TERMS = [
  "Recognized medical institutions or hospitals",
  "Adequate infrastructure for CME programme",
  "Facilities for live surgery demonstrations (optional)",
  "Commitment to AMASI standards",
]

function buildZonalProgramTitle(application: AcademicEventApplication): string {
  const zone = application.zone
  const eventName = application.event_name
  if (zone && eventName) return `AMASI ${zone} Zone Event: ${eventName}`
  if (zone) return `AMASI ${zone} Zone Event`
  if (eventName) return `AMASI Zonal Event: ${eventName}`
  return "AMASI Zonal Event"
}

function getArticleVars(application: AcademicEventApplication): ArticleVars {
  switch (application.application_type_id) {
    case "slcp":
      return {
        programTitle: "AMASI Safe Laparoscopic Cholecystectomy",
        programTagline: "One Day Interactive CME Programme",
        purposeDetail:
          "to enhance skills and knowledge in minimizing risks and improving outcomes in laparoscopic cholecystectomy",
        structureBullets: [
          "One Day Interactive CME Programme",
          "Registration: 08:30 AM",
          "Live surgery demonstrations (08:00 AM - 10:00 AM) - Optional if facilities available",
          "CME sessions start: 09:00 AM (if no live surgery) or 10:30 AM (with live surgery)",
          "Programme duration: Full day until 05:30 PM",
          "Focus on critical safety protocols, latest techniques, and best practices",
          "Expert faculty sharing insights on laparoscopic cholecystectomy",
        ],
        party1Responsibilities: SLCP_PARTY1_RESPONSIBILITIES,
        party2Responsibilities: SLCP_PARTY2_RESPONSIBILITIES,
        registrationFees: [
          "PG Students: ₹500",
          "Surgeons: ₹1000",
          "Registration managed by organizer",
          "₹500 per registration to be paid to AMASI",
        ],
        sponsorshipNote: "Optional sponsorship funds for organizers",
        facultyTerms: [
          "Qualified faculty designated by AMASI",
          "Expert surgeons with cholecystectomy expertise",
          "Travel costs borne by organizer",
          "AMASI handles all certifications",
        ],
        eligibilityTerms: SLCP_ELIGIBILITY_TERMS,
        eventNoun: "programme",
        party2Label: "PROGRAMME ORGANIZER",
      }
    case "nextgen":
      return {
        programTitle: "AMASI NextGen: Nurturing the Future",
        programTagline: "training sessions in Minimally Invasive Surgery (MAS)",
        purposeDetail: "",
        structureBullets: [
          "Training sessions limited to 35 participants",
          "7 groups of 5 candidates each",
          "Duration: 8 hours (9:00 AM - 5:00 PM)",
          "Seven training stations: Endovision System, Ergonomics, Electrosurgical, Sterilization, Pneumoperitoneum, Documentation, Endosuturing",
        ],
        party1Responsibilities: [
          "Provide curriculum guidance and quality standards",
          "Handle all participant certifications",
          "Designate 2 qualified faculty members",
          "Manage registration fees and sponsorship funds",
          "Maintain professional standards",
        ],
        party2Responsibilities: [
          "Provide venue and facilities meeting AMASI standards",
          "Arrange faculty travel and accommodation",
          "Handle logistics and participant management",
          "Submit report within 15 days",
          "Display College of MAS and AMASI logos",
          "No financial liability to AMASI",
          "Expenses to be borne by organizers or from sponsorship funds",
        ],
        registrationFees: ["Non-AMASI Members: ₹500 + GST", "AMASI Members: Free", "All payments managed by AMASI"],
        sponsorshipNote: "",
        facultyTerms: [
          "2 qualified faculty per event",
          "AMASI zonal members or state representatives",
          "Travel costs borne by organizer or the Faculty",
        ],
        eligibilityTerms: [
          "Recognized medical institutions",
          "Adequate infrastructure for 35 participants",
          "Qualified surgical faculty",
          "Commitment to AMASI standards",
        ],
        eventNoun: "training event",
        party2Label: "NEXTGEN ORGANIZER",
      }
    case "meet_the_master":
      return {
        programTitle: "AMASI Meet the Master",
        programTagline: "one day interactive academic programme",
        purposeDetail: "",
        structureBullets: ["[TBD — confirm programme structure/timing with AMASI Secretary]"],
        party1Responsibilities: SLCP_PARTY1_RESPONSIBILITIES,
        party2Responsibilities: SLCP_PARTY2_RESPONSIBILITIES,
        registrationFees: ["[TBD — confirm registration fee structure with AMASI Secretary]"],
        sponsorshipNote: "",
        facultyTerms: ["[TBD]"],
        eligibilityTerms: SLCP_ELIGIBILITY_TERMS,
        eventNoun: "programme",
        party2Label: "PROGRAMME ORGANIZER",
        placeholderNote:
          "Programme structure, registration fees, and faculty terms below are placeholders pending confirmation with the AMASI Secretary. Party responsibilities and eligibility below are provisionally reused from the SLCP programme terms as the closest sibling template — confirm before go-live.",
      }
    case "zonal_event":
      return {
        programTitle: buildZonalProgramTitle(application),
        programTagline: "zonal academic programme",
        purposeDetail: "",
        structureBullets: ["[TBD — confirm programme structure with AMASI Secretary and the zone's Chairperson]"],
        party1Responsibilities: SLCP_PARTY1_RESPONSIBILITIES,
        party2Responsibilities: SLCP_PARTY2_RESPONSIBILITIES,
        registrationFees: ["[TBD]"],
        sponsorshipNote: "",
        facultyTerms: ["[TBD — zonal events are also notified to the zone's Chairperson per the approval workflow]"],
        eligibilityTerms: SLCP_ELIGIBILITY_TERMS,
        eventNoun: "event",
        party2Label: "PROGRAMME ORGANIZER",
        placeholderNote:
          "Programme structure, registration fees, and faculty terms below are placeholders pending confirmation with the AMASI Secretary and the zone's Chairperson. Party responsibilities and eligibility below are provisionally reused from the SLCP programme terms as the closest sibling template — confirm before go-live.",
      }
    default:
      throw new Error(`getArticleVars called with unsupported application_type_id: ${application.application_type_id}`)
  }
}

function renderArticleMou(application: AcademicEventApplication) {
  const vars = getArticleVars(application)
  const purposeSentence = `To establish collaboration for conducting "${vars.programTitle}" ${vars.programTagline} across India${
    vars.purposeDetail ? ` ${vars.purposeDetail}` : ""
  }.`
  const termSentence = `This MOU becomes effective upon signing (minimum 15 days before the scheduled ${vars.eventNoun}) and automatically terminates after completion of the ${vars.eventNoun}. If the scheduled event does not take place, this MOU is automatically terminated.`

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.docTitle}>MEMORANDUM OF UNDERSTANDING</Text>
        <Text style={styles.docSubtitle}>{vars.programTitle}</Text>

        <Text style={styles.smallLabel}>Party 1: ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA (AMASI)</Text>
        <Text style={styles.paragraph}>45 A Pankaja Mill Road, Ramanathapuram, Coimbatore, Tamil Nadu 641045, India</Text>

        <Text style={styles.smallLabel}>Party 2: {vars.party2Label}</Text>
        <Text style={styles.paragraph}>
          {application.organizer_name} — {application.phone_number} — {application.email}
        </Text>

        <Acknowledgment application={application} />

        {vars.placeholderNote && <Text style={styles.placeholderNote}>{vars.placeholderNote}</Text>}

        <Text style={styles.articleHeading}>ARTICLE 1: PURPOSE</Text>
        <Text style={styles.paragraph}>{purposeSentence}</Text>

        <Text style={styles.articleHeading}>ARTICLE 2: PROGRAM STRUCTURE</Text>
        <BulletList items={vars.structureBullets} />

        <Text style={styles.articleHeading}>ARTICLE 3: RESPONSIBILITIES</Text>
        <View style={styles.twoColumnRow}>
          <View style={styles.column}>
            <Text style={styles.columnHeading}>Party 1 (AMASI):</Text>
            <BulletList items={vars.party1Responsibilities} />
          </View>
          <View style={styles.column}>
            <Text style={styles.columnHeading}>Party 2 (Organizer):</Text>
            <BulletList items={vars.party2Responsibilities} />
          </View>
        </View>

        <Text style={styles.articleHeading}>ARTICLE 4: FINANCIAL ARRANGEMENTS</Text>
        <Text style={styles.smallLabel}>Registration Fees:</Text>
        <BulletList items={vars.registrationFees} />
        <Text style={[styles.smallLabel, { marginTop: 6 }]}>Sponsorship Account:</Text>
        <Text style={styles.paragraph}>Bank: AXIS Bank, Trichy Road</Text>
        <Text style={styles.paragraph}>Account: 914010042378779</Text>
        <Text style={styles.paragraph}>IFSC: UTIB0000477</Text>
        {vars.sponsorshipNote ? <Text style={styles.paragraph}>{vars.sponsorshipNote}</Text> : null}

        <Text style={styles.articleHeading}>ARTICLE 5: FACULTY</Text>
        <BulletList items={vars.facultyTerms} />

        <Text style={styles.articleHeading}>ARTICLE 6: CERTIFICATION</Text>
        <BulletList
          items={["AMASI handles all certifications", "15-day report with photographs", "Display required logos"]}
        />

        <Text style={styles.articleHeading}>ARTICLE 7: RESTRICTIONS</Text>
        <BulletList
          items={[
            "No promotion of other organizations",
            "No personal/political propaganda",
            "Co-organizers need AMASI approval",
          ]}
        />

        <Text style={styles.articleHeading}>ARTICLE 8: ELIGIBILITY</Text>
        <BulletList items={vars.eligibilityTerms} />

        <Text style={styles.articleHeading}>ARTICLE 9: TERM</Text>
        <Text style={styles.paragraph}>{termSentence}</Text>

        <Text style={styles.articleHeading}>ARTICLE 10: CONTACT</Text>
        <Text style={styles.paragraph}>AMASI Representative: Secretary, AMASI</Text>
        <Text style={styles.paragraph}>Contact: amasi.india@gmail.com</Text>
        <Text style={styles.paragraph}>
          Organizer: {application.organizer_name}, {application.phone_number}
        </Text>

        <Text style={styles.sectionHeading}>SIGNATURES</Text>
        <View style={styles.signatureBlock}>
          <Text style={styles.signatureLine}>For Party 1 (AMASI): Secretary, AMASI</Text>
          <Text style={styles.signatureLine}>For Party 2 (Organizer): {application.organizer_name}</Text>
        </View>

        <Footer application={application} />
      </Page>
    </Document>
  )
}

// ---------------------------------------------------------------------------
// Family 3: plain numbered-clause MOU — workshop / rural_program
// ---------------------------------------------------------------------------

interface NumberedClauseTemplate {
  title: string
  roleLabel: string
  clauses: string[]
}

const WORKSHOP_CLAUSES: string[] = [
  "ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA hereinafter called AMASI being the First Party and ORGANISING COMMITTEE OF WORKSHOP/CME/CONFERENCE hereafter called OC being the second party, we the first party and the second party hereby enter in MOU as per the following details.",
  "Executive Committee of AMASI (EC) shall be the authority to represent the first party. Honorary Secretary of AMASI shall carry out all instruction of the Executive Committee of AMASI and is the authorized signatory of the first party.",
  "The authorities to present the second party shall be office bearers of Organizing Committee of the workshop/CME/conference. Organizing Secretary of the workshop/CME/conference shall act on the advice of the Organizing Committee. He is authorized to sign for the second party. The Organizing Committee is responsible for the proper conduction of the workshop/CME/conference.",
  "The venue of the workshop/CME/conference at the place already decided will be at the discretion of the OC, subject to endorsement of EC of AMASI.",
  "AMASI is holding the full right of authority to sanction any academic activities where the name 'AMASI' and Logo of AMASI will be used in any form either digital, print of both.",
  "All the banners, brochures, print materials, electronic materials associated with the event should bear the logos of both AMASI as well as ASI.",
  "A letter seeking such permission must be addressed to Secretary, AMASI HQ before announcing the programme.",
  "If the second party wishes to hold a program in any guest institution, a letter of consent from Head of the institution must be attached with request letter.",
  "If the second party wishes to hold a program individually in private institution, he / she must attach a brief about the institution.",
  "If the second party proposes to hold any program jointly with other association, a letter of consent form of the partner association must be attached with request letter.",
  "AMASI HQ will complete the official processing of such request latest by two weeks after receiving such request.",
  "There is no option/permission to open of any Bank Account in the name of AMASI in any form in any circumstances for such workshops/CME/conferences.",
  "The Second Party will decide the programme of the Workshop/CME/conference, only after approval of the first party. This includes selection of speakers, subjects, timings, allotment of halls, chairman etc. The second party shall make arrangements for the conduction of the workshop/CME/conference. It includes providing halls of adequate capacity, audiovisual equipment and management, suitable podium and personnel for assistance.",
  "All the faculties at such workshop/CME/conference have to be bonafide members of AMASI. Exceptions can be made for faculties belonging to other specialities like anesthetists, gynecologists, urologists, gastroenterologists, etc. after prior intimation to the first party.",
  "The Second Party can fix a reasonable registration fee for the workshop/CME/conference after approval of the first party.",
  "The second party shall arrange to and fro transport of the faculties provided by AMASI and their accommodation and food. The second party can either ask the faculties to book their own transport and re-imburse them at the venue of the workshop/CME/conference or can directly book the airline/train tickets for the faculties as per a mutually suitable itinerary.",
  "However, an exception is made for academic events organized by state chapters of small states to promote academics in such states. In these states, AMASI shall provide the to and fro transport for 2-3 of its faculties. The local hospitality, accomodation and food of these faculties shall still remain the responsibility of the organizers. The states in which these exceptions are made are as under: a) Jammu & Kashmir b) Uttarakhand c) Himachal Pradesh d) Tripura e) Meghalaya f) Manipur g) Nagaland h) Arunachal Pradhesh i) Mizoram j) Sikkim.",
  "The Second party shall not display any audiovisual material at the venue to promote meeting, conferences, workshops of any other professional body without intimating the first party.",
  "The second party shall not utilize the workshop/CME/conference for personal propaganda, promotion of their private hospital, political propaganda or purpose other than academic dissemination of knowledge.",
  "The second party shall bear the full financial responsibility of the event. The first party shall not in any way bear financial liabilities for the workshop/CME/conference. The second party also in not liable to make any payment to the first party for the same.",
  "The Second Party shall forward a detailed program listing all the members of the OC, the schedule of lectures/operations and the faculties involved to the first party at least 3 weeks before the commencement of the event.",
  "The first party will display the event and its schedule including links for registration for the event if provided by the first party on it website. For this, the full details have to be submitted by the second party to the first party at least 3 weeks prior to the event.",
  "If such a facility is available, the first party will send an email circular to its members who have registered their emails with the first party intimating them of the event provided the second party submits such details in appropriate format to the first party at least 3 weeks prior to the event.",
  "The Second Party shall maintain close liaison with the First party. Organizing Secretary shall provide full details of the facilities available for the workshop/CME/conference to Hon. Secretary of AMASI at least 1month in advance. The full responsibility of conducting the workshop/CME/conference will rest with the second party and AMASI will in no way liable or answerable to the delegates.",
  "The Organizing Secretary shall submit a report to Hony. Secretary AMASI after conclusion of the workshop/CME/conference. It should include workshop/CME/conference photographs, The report should reach Hony. Secretary, AMASI within fifteen days.",
  "This Memorandum of Understanding has to be signed by the Organizing Secretary of the workshop/CME/conference on behalf of the Second party. Hony. Secretary of AMASI has to sign on behalf of the First party. If the Organizing Secretary of selected workshop/CME/conference fails to sign the Memorandum of Understanding at least 15 days prior to the event, invitation stands cancelled and Second Party shall not use the logo or name of the first party for any such event.",
]

const RURAL_PROGRAM_CLAUSES: string[] = [
  "ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA hereinafter called AMASI being the First Party and ORGANISING COMMITTEE OF RURAL SURGICAL CAMP hereafter called OC being the second party, we the first party and the second party hereby enter in MOU as per the following details.",
  "Executive Committee of AMASI (EC) shall be the authority to represent the first party. Honorary Secretary of AMASI shall carry out all instruction of the Executive Committee of AMASI and is the authorized signatory of the first party.",
  "The authorities to present the second party shall be office bearers of Organizing Committee of the rural surgical camp. Organizing Secretary of the rural surgical camp shall act on the advice of the Organizing Committee. He is authorized to sign for the second party. The Organizing Committee is responsible for the proper conduction of the rural surgical camp.",
  "The venue of the rural surgical camp at the place already decided will be at the discretion of the OC, subject to endorsement of EC of AMASI. However, the camp has to be in a hospital located in a rural setting and not in any urban area.",
  "AMASI is holding the full right of authority to sanction any academic activities where the name 'AMASI' and Logo of AMASI will be used in any form either digital, print or both.",
  "A letter seeking such permission must be addressed to Secretary, AMASI HQ before announcing the programme.",
  "All the banners, brochures, print materials, electronic materials associated with the event should bear the logos of both AMASI as well as ASI.",
  "If the second party wishes to hold a program in any guest institution, a letter of consent from Head of the institution must be attached with request letter.",
  "If the second party wishes to hold a program individually in private institution, he / she must attach a brief about the institution.",
  "If the second party proposes to hold any program jointly with other association, a letter of consent form of the partner association must be attached with request letter.",
  "AMASI HQ will complete the official processing of such request latest by two weeks after receiving such request.",
  "There is no option/permission to open of any Bank Account in the name of AMASI in any form in any circumstances for such workshops/CME/conferences.",
  "The Second Party will decide the programme of the Rural surgical camp, only after approval of the first party. The second party shall make arrangements for the conduction of the rural surgical camp. It includes arranging appropriate instruments, disposables, and personnel for assistance. The second party may solicit the support of pharmaceutical companies, surgical goods manufacturers and private individuals for donation in cash or kind for the same.",
  "All the faculties at such rural surgical camp have to be bonafide members of AMASI. Exceptions can be made for faculties belonging to other specialities like anesthetists, gynecologists, urologists, gastroenterologists, etc. after prior intimation to the first party.",
  "The Second Party can fix a reasonable registration fee for the rural surgical camp after approval of the first party.",
  "The second party shall arrange to and fro transport of the faculties provided by AMASI from the nearest railhead or airport and their accommodation and food. The faculties shall reach the nearest railhead/airport at their own expense on request of the first party.",
  "The Second party shall not display any audiovisual material at the venue to promote meeting, conferences, workshops of any other professional body without intimating the first party.",
  "The second party shall not utilize the rural surgical camp for personal propaganda, promotion of their private hospital, political propaganda or purpose other than service to the population.",
  "The second party shall bear the full financial responsibility of the event. The first party shall not in any way bear financial liabilities for the rural surgical camp. The second party also in not liable to make any payment to the first party for the same.",
  "For rural surgical camp, AMASI shall provide financial assistance upto Rs. One lakh only, on receiving the original bills and vouchers.",
  "The Second Party shall forward a detailed program listing all the members of the OC, the schedule of lectures/operations and the faculties involved to the first party at least 3 weeks before the commencement of the event.",
  "The first party will display the event and its schedule including links for registration for the event if provided by the first party on it website. For this, the full details have to be submitted by the second party to the first party at least 3 weeks prior to the event.",
  "The Second Party shall maintain close liaison with the First party. Organizing Secretary shall provide full details of the facilities available for the rural surgical camp to Hon. Secretary of AMASI at least 1month in advance. The full responsibility of conducting the rural surgical camp will rest with the second party and AMASI will in no way liable or answerable to the beneficiaries of such a camp.",
  "The Organizing Secretary shall submit a report to Hony. Secretary AMASI after conclusion of the rural surgical camp. It should include rural surgical camp photographs, the location of the camp, a brief description of the beneficiaries of the camp, the total number of surgeries performed. The report should reach Hony. Secretary, AMASI within fifteen days.",
  "This Memorandum of Understanding has to be signed by the Organizing Secretary of the rural surgical camp on behalf of the Second party. Hony. Secretary of AMASI has to sign on behalf of the First party. If the Organizing Secretary of selected rural surgical camp fails to sign the Memorandum of Understanding at least 15 days prior to the event, invitation stands cancelled and Second Party shall not use the logo or name of the first party for any such event.",
]

function getNumberedClauseTemplate(typeId: ApplicationTypeId): NumberedClauseTemplate {
  if (typeId === "workshop") {
    return {
      title: "MEMORANDUM OF UNDERSTANDING FOR WORKSHOP/CME/CONFERENCE (OTHER THAN AMASICON)",
      roleLabel: "workshop/CME/conference",
      clauses: WORKSHOP_CLAUSES,
    }
  }
  return {
    title: "MEMORANDUM OF UNDERSTANDING FOR RURAL SURGERY CAMP",
    roleLabel: "rural surgical camp",
    clauses: RURAL_PROGRAM_CLAUSES,
  }
}

function renderNumberedClauseMou(application: AcademicEventApplication) {
  const template = getNumberedClauseTemplate(application.application_type_id)

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.letterheadOrg}>ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA</Text>
        <Text style={styles.letterheadTitle}>{template.title}</Text>
        <Text style={styles.letterheadContact}>
          AMASI Head Office 45 A, Pankaja Mill Rd, Ramanathapuram, Coimbatore, +914224223330 amasi.india@gmail.com
          www.amasi.org
        </Text>

        <Acknowledgment application={application} />

        {template.clauses.map((clause, i) => (
          <View style={styles.clauseRow} key={i}>
            <Text style={styles.clauseNum}>{i + 1}.</Text>
            <Text style={styles.clauseText}>{clause}</Text>
          </View>
        ))}

        <View style={styles.signatureBlock}>
          <Text style={styles.signatureLine}>Signed: _________________ (Hon Secretary of AMASI)</Text>
          <Text style={styles.signatureLine}>
            Signed: {application.organizer_name} (Organizing Secretary of {template.roleLabel})
          </Text>
        </View>

        <Footer application={application} />
      </Page>
    </Document>
  )
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const COLLEGE_OF_MAS_TYPES: ApplicationTypeId[] = ["fmas", "mmas", "dmas"]
const ARTICLE_TYPES: ApplicationTypeId[] = ["slcp", "nextgen", "meet_the_master", "zonal_event"]
const NUMBERED_CLAUSE_TYPES: ApplicationTypeId[] = ["workshop", "rural_program"]

export async function generateMouPdf(application: AcademicEventApplication, typeLabel: string): Promise<Buffer> {
  let doc: React.ReactElement<DocumentProps>

  if (COLLEGE_OF_MAS_TYPES.includes(application.application_type_id)) {
    doc = renderCollegeOfMasMou(application, typeLabel)
  } else if (ARTICLE_TYPES.includes(application.application_type_id)) {
    doc = renderArticleMou(application)
  } else if (NUMBERED_CLAUSE_TYPES.includes(application.application_type_id)) {
    doc = renderNumberedClauseMou(application)
  } else {
    throw new Error(`generateMouPdf: unsupported application_type_id "${application.application_type_id}"`)
  }

  return renderToBuffer(doc)
}
