import React from "react"
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer"
import type { AcademicEventApplication } from "./types"

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  title: { fontSize: 16, marginBottom: 4, textAlign: "center" },
  subtitle: { fontSize: 10, marginBottom: 20, textAlign: "center", color: "#555" },
  row: { flexDirection: "row", marginBottom: 6 },
  label: { width: 180, fontWeight: 700 },
  value: { flex: 1 },
  section: { marginTop: 16, marginBottom: 8, fontSize: 12, fontWeight: 700 },
  footer: { marginTop: 40, fontSize: 9, color: "#777" },
})

function Row({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  )
}

export async function generateMouPdf(application: AcademicEventApplication, typeLabel: string): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Memorandum of Understanding</Text>
        <Text style={styles.subtitle}>{typeLabel} — Association of Minimal Access Surgeons of India</Text>

        <Text style={styles.section}>Organizer</Text>
        <Row label="Name" value={application.organizer_name} />
        <Row label="Institution" value={application.primary_institution} />
        <Row label="Email" value={application.email} />
        <Row label="Phone" value={application.phone_number} />
        {application.applicant_amasi_number && (
          <Row label="AMASI Membership No." value={application.applicant_amasi_number} />
        )}

        <Text style={styles.section}>Event</Text>
        <Row label="Finalized Date" value={application.finalized_date ?? application.preferred_date_1} />
        <Row label="Venue" value={[application.venue_name, application.venue_city, application.venue_state].filter(Boolean).join(", ")} />

        <Text style={styles.section}>Acknowledgment</Text>
        <Text>
          This application was verified by a one-time code sent to the organizer&apos;s registered contact on{" "}
          {application.otp_verified_at ? new Date(application.otp_verified_at).toLocaleString("en-IN") : "N/A"}, and
          approved by {application.reviewed_by ?? "the AMASI Hon. Secretary"} on{" "}
          {application.reviewed_at ? new Date(application.reviewed_at).toLocaleString("en-IN") : "N/A"}.
        </Text>

        <Text style={styles.footer}>
          Generated by AMASI Membership Portal — Application ID {application.id} — Version {application.mou_version + 1}
        </Text>
      </Page>
    </Document>
  )
  return renderToBuffer(doc)
}
