import React from "react"
import { Document, Page, Text, View, StyleSheet, renderToBuffer, type DocumentProps } from "@react-pdf/renderer"
import type { AcademicEventApplication, ApplicationTypeId, MouSignature } from "./types"

const styles = StyleSheet.create({
  page: { padding: 40, paddingBottom: 56, fontSize: 10, fontFamily: "Helvetica", lineHeight: 1.4 },
  docTitle: { fontSize: 14, marginBottom: 4, textAlign: "center" },
  docSubtitle: { fontSize: 9, marginBottom: 14, textAlign: "center", color: "#555" },
  sectionHeading: { fontSize: 11, fontWeight: 700, marginTop: 14, marginBottom: 6 },
  articleHeading: { fontSize: 11, fontWeight: 700, marginTop: 14, marginBottom: 6 },
  clauseRow: { flexDirection: "row", marginBottom: 5 },
  clauseNum: { width: 18, fontWeight: 700 },
  clauseText: { flex: 1 },
  subBullet: { marginLeft: 22, marginBottom: 3 },
  bulletRow: { flexDirection: "row", marginBottom: 3 },
  bulletMark: { width: 10 },
  bulletText: { flex: 1 },
  paragraph: { marginBottom: 6 },
  smallLabel: { fontWeight: 700 },
  ackBox: {
    marginTop: 8,
    marginBottom: 14,
    padding: 8,
    fontSize: 8.5,
    fontStyle: "italic",
    color: "#333",
    borderWidth: 1,
    borderColor: "#ccc",
    borderStyle: "solid",
  },
  placeholderNote: {
    marginBottom: 8,
    fontSize: 9,
    fontStyle: "italic",
    color: "#8a5a00",
  },
  twoColumnRow: { flexDirection: "row", marginBottom: 8 },
  column: { flex: 1, paddingRight: 10 },
  columnHeading: { fontWeight: 700, marginBottom: 4 },
  signatureBlock: { marginTop: 18 },
  signatureLine: { marginBottom: 4 },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#777",
    textAlign: "center",
    paddingTop: 4,
    borderTopWidth: 0.5,
    borderTopColor: "#ccc",
    borderTopStyle: "solid",
  },
  letterheadOrg: { fontSize: 12, fontWeight: 700, textAlign: "center" },
  letterheadTitle: { fontSize: 11, fontWeight: 700, textAlign: "center", marginTop: 4 },
  letterheadContact: { fontSize: 8, textAlign: "center", marginTop: 4, marginBottom: 14, color: "#555" },
})

function formatDate(value: string | null): string {
  return value ? new Date(value).toLocaleString("en-IN") : "N/A"
}

function Acknowledgment({ application }: { application: AcademicEventApplication }) {
  return (
    <View style={styles.ackBox}>
      <Text>
        This application was verified by a one-time code sent to the organizer&apos;s registered contact on{" "}
        {formatDate(application.otp_verified_at)}, and approved by{" "}
        {application.reviewed_by ?? "the AMASI Hon. Secretary"} on {formatDate(application.reviewed_at)}.
      </Text>
    </View>
  )
}

function Footer({ application }: { application: AcademicEventApplication }) {
  return (
    <Text style={styles.footer} fixed>
      Generated by AMASI Membership Portal — Application ID {application.id} — Version{" "}
      {application.mou_version + 1}
    </Text>
  )
}

function BulletList({ items }: { items: string[] }) {
  return (
    <>
      {items.map((item, i) => (
        <View style={styles.bulletRow} key={i}>
          <Text style={styles.bulletMark}>{"•"}</Text>
          <Text style={styles.bulletText}>{item}</Text>
        </View>
      ))}
    </>
  )
}

// ---------------------------------------------------------------------------
// Family 1: "College of MAS" numbered-section MOU — fmas / mmas / dmas
// ---------------------------------------------------------------------------

const COLLEGE_OF_MAS_COURSE_NAMES: Record<"fmas" | "mmas" | "dmas", string> = {
  fmas: "FMAS Skill Course",
  mmas: "MMAS Skill Course",
  dmas: "DMAS Skill Course",
}

interface ClauseItem {
  text: string
  subBullets?: string[]
}

interface ClauseSection {
  heading: string
  clauses: ClauseItem[]
}

function buildCollegeOfMasSections(course: string): ClauseSection[] {
  return [
    {
      heading: "PARTIES AND AUTHORITY",
      clauses: [
        {
          text: `COLLEGE OF AMASI, hereinafter called "College of MAS" (First Party) and ORGANIZING COMMITTEE OF ${course}, called "Convenor" (Second Party), enter into this MOU.`,
        },
        {
          text: `Secretary College of MAS is the authorized signatory or a person designated by college of MAS and decision-making authority for the First Party. The Convenor of ${course} represents the Second Party.`,
        },
      ],
    },
    {
      heading: "COURSE APPROVAL AND SCHEDULING",
      clauses: [
        {
          text: "Process: MOU submission → Date availability check → Approval from Secretary College of MAS or a person designated by college of MAS → Course announcement. Convenor selects venues subject to Secretary's endorsement.",
        },
        {
          text: "Requirements: College of MAS maintains full authority over name and logo usage. All materials must display College of MAS + AMASI.",
        },
      ],
    },
    {
      heading: "DIVISION OF RESPONSIBILITIES",
      clauses: [
        {
          text: "College of MAS (Head Office):",
          subBullets: [
            "Flyer, brochure, website management, and online registration",
            "Scientific program, faculty selection, e-badge preparation",
            "OMR sheets, question papers, certificates, feedback collection",
            "Financial management and vendor payments",
          ],
        },
        {
          text: "Organizing Committee:",
          subBullets: [
            "Venue, accommodation, catering, local transport arrangements",
            "AV setup, seating, signage, endotrainer setup for examination",
            "Faculty hospitality, kit distribution, local coordination",
          ],
        },
        {
          text: "Faculty: Must be AMASI members or approved by College of MAS/AMASI. Exceptions for other specialties require prior approval.",
        },
      ],
    },
    {
      heading: "PROGRAM SUBMISSION AND COORDINATION",
      clauses: [
        {
          text: "Timeline: Convener submits detailed program (committee members, venue, logistics) 6 weeks before the event. College of MAS provides faculty details and allotment of their topic 1 month in advance.",
        },
        {
          text: "Coordination: Secretary College of MAS/AMASI approval required before scientific program execution. Continuous coordination between both parties throughout preparation.",
        },
      ],
    },
    {
      heading: "FINANCIAL MANAGEMENT",
      clauses: [
        { text: "Banking: All transactions through College of MAS accounts only. Convenor may not maintain separate accounts." },
        {
          text: "Sponsorship: Convenor may receive sponsorships but all funds must be deposited in the College of MAS account. All payments will be processed through College of MAS. Sponsorship must cover any additional amount for example course dinner.",
        },
        {
          text: "Advance Payments: For hotels/catering, Convenor submits quotations and receives up to 75% advance. Balance paid after service completion. All the payments will be made directly to the vendor only.",
        },
        {
          text: "Documentation: Bills above Rs.50/- required. Bills above Rs.30,000/- require Company PAN or 20% TDS deduction. College of MAS handles verification and direct vendor payments.",
        },
        {
          text: "Registration: Managed through College of MAS website. Dashboard access provided to Convenor for real-time monitoring of participants and payments.",
        },
      ],
    },
    {
      heading: "ACADEMIC STANDARDS",
      clauses: [
        { text: "Curriculum: Scientific program standardized by College of MAS. No content changes without approval." },
        { text: "Examination: College of MAS prepares OMR sheets/question papers. Convenor sets up endo trainers." },
      ],
    },
    {
      heading: "REPORTING AND COMPLIANCE",
      clauses: [
        {
          text: "Post-Event: Convenor submits a comprehensive report with photographs within 15 days. All materials must display College of MAS and AMASI logos.",
        },
        { text: "Restrictions: No promotion of other organizations without permission. No personal/political propaganda permitted." },
        { text: "Other academic Association can be co organiser only after approval from Head office." },
      ],
    },
    {
      heading: "CANCELLATION AND SIGNATURES",
      clauses: [{ text: "Deadline: MOU must be signed at least 30 days before the event, or automatic cancellation applies." }],
    },
  ]
}

function CollegeOfMasSection({ section }: { section: ClauseSection }) {
  return (
    <View>
      <Text style={styles.sectionHeading}>{section.heading}</Text>
      {section.clauses.map((clause, i) => (
        <View key={i}>
          <View style={styles.clauseRow}>
            <Text style={styles.clauseNum}>{i + 1}.</Text>
            <Text style={styles.clauseText}>{clause.text}</Text>
          </View>
          {clause.subBullets?.map((sub, j) => (
            <View style={styles.bulletRow} key={j}>
              <Text style={[styles.bulletMark, styles.subBullet]}>{"–"}</Text>
              <Text style={styles.bulletText}>{sub}</Text>
            </View>
          ))}
        </View>
      ))}
    </View>
  )
}

function renderCollegeOfMasMou(application: AcademicEventApplication, typeLabel: string) {
  const typeId = application.application_type_id as "fmas" | "mmas" | "dmas"
  const course = COLLEGE_OF_MAS_COURSE_NAMES[typeId] ?? typeLabel
  const sections = buildCollegeOfMasSections(course)

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.docTitle}>MEMORANDUM OF UNDERSTANDING FOR {course}</Text>
        <Text style={styles.docSubtitle}>
          Headquarters: GEM Hospital, 45-A, Pankaja Mill Road, Ramanathapuram, Coimbatore - 641 045
        </Text>

        <Acknowledgment application={application} />

        {sections.map((section, i) => (
          <CollegeOfMasSection section={section} key={i} />
        ))}

        <View style={styles.signatureBlock}>
          <Text style={styles.signatureLine}>First Party: Secretary College of MAS</Text>
          <Text style={styles.signatureLine}>
            Second Party: {application.organizer_name} (Convenor, {course})
          </Text>
        </View>

        <Text style={styles.sectionHeading}>Billing / Sponsorship Account</Text>
        <Text style={styles.paragraph}>
          Bill To: College of AMASI, Address: 45 A Pankaja Mill Road, Ramanathapuram, Coimbatore, TN (33) 641045,
          IN. GSTIN: 33AABTC9091L1ZF
        </Text>
        <Text style={styles.paragraph}>
          Sponsorship Payment: Account Name: College of AMASI, Bank Name: AXIS Bank, Branch Name: TRICHY ROAD
          BRANCH, Account Number: 916020034964055, IFSC Code: UTIB000047
        </Text>

        <Footer application={application} />
      </Page>
    </Document>
  )
}

// ---------------------------------------------------------------------------
// Family 2: "Article" MOU — slcp / nextgen / meet_the_master / zonal_event
// ---------------------------------------------------------------------------

interface ArticleVars {
  programTitle: string
  programTagline: string
  purposeDetail: string
  structureBullets: string[]
  party1Responsibilities: string[]
  party2Responsibilities: string[]
  registrationFees: string[]
  sponsorshipNote: string
  facultyTerms: string[]
  eligibilityTerms: string[]
  eventNoun: string
  party2Label: string
  placeholderNote?: string
}

const SLCP_PARTY1_RESPONSIBILITIES = [
  "Provide curriculum guidance and quality standards",
  "Handle all participant certifications",
  "Designate qualified faculty members",
  "Receive ₹500 per registration from organizer",
  "Provide academic material for use in the program",
  "Maintain professional standards",
  "Provide program endorsement and branding",
]

const SLCP_PARTY2_RESPONSIBILITIES = [
  "Provide venue and facilities meeting AMASI standards",
  "Arrange faculty travel and accommodation",
  "May propose faculties which must be finalized by AMASI headquarters",
  "Will not divert from academic content without prior permission from National Director, AMASI Safe Lap Chole Program",
  "Handle logistics and participant management",
  "Submit report within 15 days",
  "Display College of MAS and AMASI logos",
  "Pay ₹500 per registration to AMASI",
  "Expenses to be borne by organizers or from sponsorship funds",
]

const SLCP_ELIGIBILITY_TERMS = [
  "Recognized medical institutions or hospitals",
  "Adequate infrastructure for CME programme",
  "Facilities for live surgery demonstrations (optional)",
  "Commitment to AMASI standards",
]

function buildZonalProgramTitle(application: AcademicEventApplication): string {
  const zone = application.zone
  const eventName = application.event_name
  if (zone && eventName) return `AMASI ${zone} Zone Event: ${eventName}`
  if (zone) return `AMASI ${zone} Zone Event`
  if (eventName) return `AMASI Zonal Event: ${eventName}`
  return "AMASI Zonal Event"
}

function getArticleVars(application: AcademicEventApplication): ArticleVars {
  switch (application.application_type_id) {
    case "slcp":
      return {
        programTitle: "AMASI Safe Laparoscopic Cholecystectomy",
        programTagline: "One Day Interactive CME Programme",
        purposeDetail:
          "to enhance skills and knowledge in minimizing risks and improving outcomes in laparoscopic cholecystectomy",
        structureBullets: [
          "One Day Interactive CME Programme",
          "Registration: 08:30 AM",
          "Live surgery demonstrations (08:00 AM - 10:00 AM) - Optional if facilities available",
          "CME sessions start: 09:00 AM (if no live surgery) or 10:30 AM (with live surgery)",
          "Programme duration: Full day until 05:30 PM",
          "Focus on critical safety protocols, latest techniques, and best practices",
          "Expert faculty sharing insights on laparoscopic cholecystectomy",
        ],
        party1Responsibilities: SLCP_PARTY1_RESPONSIBILITIES,
        party2Responsibilities: SLCP_PARTY2_RESPONSIBILITIES,
        registrationFees: [
          "PG Students: ₹500",
          "Surgeons: ₹1000",
          "Registration managed by organizer",
          "₹500 per registration to be paid to AMASI",
        ],
        sponsorshipNote: "Optional sponsorship funds for organizers",
        facultyTerms: [
          "Qualified faculty designated by AMASI",
          "Expert surgeons with cholecystectomy expertise",
          "Travel costs borne by organizer",
          "AMASI handles all certifications",
        ],
        eligibilityTerms: SLCP_ELIGIBILITY_TERMS,
        eventNoun: "programme",
        party2Label: "PROGRAMME ORGANIZER",
      }
    case "nextgen":
      return {
        programTitle: "AMASI NextGen: Nurturing the Future",
        programTagline: "training sessions in Minimally Invasive Surgery (MAS)",
        purposeDetail: "",
        structureBullets: [
          "Training sessions limited to 35 participants",
          "7 groups of 5 candidates each",
          "Duration: 8 hours (9:00 AM - 5:00 PM)",
          "Seven training stations: Endovision System, Ergonomics, Electrosurgical, Sterilization, Pneumoperitoneum, Documentation, Endosuturing",
        ],
        party1Responsibilities: [
          "Provide curriculum guidance and quality standards",
          "Handle all participant certifications",
          "Designate 2 qualified faculty members",
          "Manage registration fees and sponsorship funds",
          "Maintain professional standards",
        ],
        party2Responsibilities: [
          "Provide venue and facilities meeting AMASI standards",
          "Arrange faculty travel and accommodation",
          "Handle logistics and participant management",
          "Submit report within 15 days",
          "Display College of MAS and AMASI logos",
          "No financial liability to AMASI",
          "Expenses to be borne by organizers or from sponsorship funds",
        ],
        registrationFees: ["Non-AMASI Members: ₹500 + GST", "AMASI Members: Free", "All payments managed by AMASI"],
        sponsorshipNote: "",
        facultyTerms: [
          "2 qualified faculty per event",
          "AMASI zonal members or state representatives",
          "Travel costs borne by organizer or the Faculty",
        ],
        eligibilityTerms: [
          "Recognized medical institutions",
          "Adequate infrastructure for 35 participants",
          "Qualified surgical faculty",
          "Commitment to AMASI standards",
        ],
        eventNoun: "training event",
        party2Label: "NEXTGEN ORGANIZER",
      }
    case "meet_the_master":
      return {
        programTitle: "AMASI Meet the Master",
        programTagline: "one day interactive academic programme",
        purposeDetail: "",
        structureBullets: ["[TBD — confirm programme structure/timing with AMASI Secretary]"],
        party1Responsibilities: SLCP_PARTY1_RESPONSIBILITIES,
        party2Responsibilities: SLCP_PARTY2_RESPONSIBILITIES,
        registrationFees: ["[TBD — confirm registration fee structure with AMASI Secretary]"],
        sponsorshipNote: "",
        facultyTerms: ["[TBD]"],
        eligibilityTerms: SLCP_ELIGIBILITY_TERMS,
        eventNoun: "programme",
        party2Label: "PROGRAMME ORGANIZER",
        placeholderNote:
          "Programme structure, registration fees, and faculty terms below are placeholders pending confirmation with the AMASI Secretary. Party responsibilities and eligibility below are provisionally reused from the SLCP programme terms as the closest sibling template — confirm before go-live.",
      }
    case "zonal_event":
      return {
        programTitle: buildZonalProgramTitle(application),
        programTagline: "zonal academic programme",
        purposeDetail: "",
        structureBullets: ["[TBD — confirm programme structure with AMASI Secretary and the zone's Chairperson]"],
        party1Responsibilities: SLCP_PARTY1_RESPONSIBILITIES,
        party2Responsibilities: SLCP_PARTY2_RESPONSIBILITIES,
        registrationFees: ["[TBD]"],
        sponsorshipNote: "",
        facultyTerms: ["[TBD — zonal events are also notified to the zone's Chairperson per the approval workflow]"],
        eligibilityTerms: SLCP_ELIGIBILITY_TERMS,
        eventNoun: "event",
        party2Label: "PROGRAMME ORGANIZER",
        placeholderNote:
          "Programme structure, registration fees, and faculty terms below are placeholders pending confirmation with the AMASI Secretary and the zone's Chairperson. Party responsibilities and eligibility below are provisionally reused from the SLCP programme terms as the closest sibling template — confirm before go-live.",
      }
    default:
      throw new Error(`getArticleVars called with unsupported application_type_id: ${application.application_type_id}`)
  }
}

function renderArticleMou(application: AcademicEventApplication) {
  const vars = getArticleVars(application)
  const purposeSentence = `To establish collaboration for conducting "${vars.programTitle}" ${vars.programTagline} across India${
    vars.purposeDetail ? ` ${vars.purposeDetail}` : ""
  }.`
  const termSentence = `This MOU becomes effective upon signing (minimum 15 days before the scheduled ${vars.eventNoun}) and automatically terminates after completion of the ${vars.eventNoun}. If the scheduled event does not take place, this MOU is automatically terminated.`

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.docTitle}>MEMORANDUM OF UNDERSTANDING</Text>
        <Text style={styles.docSubtitle}>{vars.programTitle}</Text>

        <Text style={styles.smallLabel}>Party 1: ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA (AMASI)</Text>
        <Text style={styles.paragraph}>45 A Pankaja Mill Road, Ramanathapuram, Coimbatore, Tamil Nadu 641045, India</Text>

        <Text style={styles.smallLabel}>Party 2: {vars.party2Label}</Text>
        <Text style={styles.paragraph}>
          {application.organizer_name} — {application.phone_number} — {application.email}
        </Text>

        <Acknowledgment application={application} />

        {vars.placeholderNote && <Text style={styles.placeholderNote}>{vars.placeholderNote}</Text>}

        <Text style={styles.articleHeading}>ARTICLE 1: PURPOSE</Text>
        <Text style={styles.paragraph}>{purposeSentence}</Text>

        <Text style={styles.articleHeading}>ARTICLE 2: PROGRAM STRUCTURE</Text>
        <BulletList items={vars.structureBullets} />

        <Text style={styles.articleHeading}>ARTICLE 3: RESPONSIBILITIES</Text>
        <View style={styles.twoColumnRow}>
          <View style={styles.column}>
            <Text style={styles.columnHeading}>Party 1 (AMASI):</Text>
            <BulletList items={vars.party1Responsibilities} />
          </View>
          <View style={styles.column}>
            <Text style={styles.columnHeading}>Party 2 (Organizer):</Text>
            <BulletList items={vars.party2Responsibilities} />
          </View>
        </View>

        <Text style={styles.articleHeading}>ARTICLE 4: FINANCIAL ARRANGEMENTS</Text>
        <Text style={styles.smallLabel}>Registration Fees:</Text>
        <BulletList items={vars.registrationFees} />
        <Text style={[styles.smallLabel, { marginTop: 6 }]}>Sponsorship Account:</Text>
        <Text style={styles.paragraph}>Bank: AXIS Bank, Trichy Road</Text>
        <Text style={styles.paragraph}>Account: 914010042378779</Text>
        <Text style={styles.paragraph}>IFSC: UTIB0000477</Text>
        {vars.sponsorshipNote ? <Text style={styles.paragraph}>{vars.sponsorshipNote}</Text> : null}

        <Text style={styles.articleHeading}>ARTICLE 5: FACULTY</Text>
        <BulletList items={vars.facultyTerms} />

        <Text style={styles.articleHeading}>ARTICLE 6: CERTIFICATION</Text>
        <BulletList
          items={["AMASI handles all certifications", "15-day report with photographs", "Display required logos"]}
        />

        <Text style={styles.articleHeading}>ARTICLE 7: RESTRICTIONS</Text>
        <BulletList
          items={[
            "No promotion of other organizations",
            "No personal/political propaganda",
            "Co-organizers need AMASI approval",
          ]}
        />

        <Text style={styles.articleHeading}>ARTICLE 8: ELIGIBILITY</Text>
        <BulletList items={vars.eligibilityTerms} />

        <Text style={styles.articleHeading}>ARTICLE 9: TERM</Text>
        <Text style={styles.paragraph}>{termSentence}</Text>

        <Text style={styles.articleHeading}>ARTICLE 10: CONTACT</Text>
        <Text style={styles.paragraph}>AMASI Representative: Secretary, AMASI</Text>
        <Text style={styles.paragraph}>Contact: amasi.india@gmail.com</Text>
        <Text style={styles.paragraph}>
          Organizer: {application.organizer_name}, {application.phone_number}
        </Text>

        <Text style={styles.sectionHeading}>SIGNATURES</Text>
        <View style={styles.signatureBlock}>
          <Text style={styles.signatureLine}>For Party 1 (AMASI): Secretary, AMASI</Text>
          <Text style={styles.signatureLine}>For Party 2 (Organizer): {application.organizer_name}</Text>
        </View>

        <Footer application={application} />
      </Page>
    </Document>
  )
}

// ---------------------------------------------------------------------------
// Family 3: plain numbered-clause MOU — workshop / rural_program
// ---------------------------------------------------------------------------

interface NumberedClauseTemplate {
  title: string
  roleLabel: string
  clauses: string[]
  // Optional trailing procedure sheet (AMASICON's "Procedures to be
  // followed" page). Rendered after the numbered clauses, before the
  // signature block, so it is part of the signed document.
  appendix?: { title: string; sections: { heading: string; items: string[] }[] }
}

export const WORKSHOP_CLAUSES: string[] = [
  "ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA hereinafter called AMASI being the First Party and ORGANISING COMMITTEE OF WORKSHOP/CME/CONFERENCE hereafter called OC being the second party, we the first party and the second party hereby enter in MOU as per the following details.",
  "Executive Committee of AMASI (EC) shall be the authority to represent the first party. Honorary Secretary of AMASI shall carry out all instruction of the Executive Committee of AMASI and is the authorized signatory of the first party.",
  "The authorities to present the second party shall be office bearers of Organizing Committee of the workshop/CME/conference. Organizing Secretary of the workshop/CME/conference shall act on the advice of the Organizing Committee. He is authorized to sign for the second party. The Organizing Committee is responsible for the proper conduction of the workshop/CME/conference.",
  "The venue of the workshop/CME/conference at the place already decided will be at the discretion of the OC, subject to endorsement of EC of AMASI.",
  "AMASI is holding the full right of authority to sanction any academic activities where the name 'AMASI' and Logo of AMASI will be used in any form either digital, print of both.",
  "All the banners, brochures, print materials, electronic materials associated with the event should bear the logos of both AMASI as well as ASI.",
  "A letter seeking such permission must be addressed to Secretary, AMASI HQ before announcing the programme.",
  "If the second party wishes to hold a program in any guest institution, a letter of consent from Head of the institution must be attached with request letter.",
  "If the second party wishes to hold a program individually in private institution, he / she must attach a brief about the institution.",
  "If the second party proposes to hold any program jointly with other association, a letter of consent form of the partner association must be attached with request letter.",
  "AMASI HQ will complete the official processing of such request latest by two weeks after receiving such request.",
  "There is no option/permission to open of any Bank Account in the name of AMASI in any form in any circumstances for such workshops/CME/conferences.",
  "The Second Party will decide the programme of the Workshop/CME/conference, only after approval of the first party. This includes selection of speakers, subjects, timings, allotment of halls, chairman etc. The second party shall make arrangements for the conduction of the workshop/CME/conference. It includes providing halls of adequate capacity, audiovisual equipment and management, suitable podium and personnel for assistance.",
  "All the faculties at such workshop/CME/conference have to be bonafide members of AMASI. Exceptions can be made for faculties belonging to other specialities like anesthetists, gynecologists, urologists, gastroenterologists, etc. after prior intimation to the first party.",
  "The Second Party can fix a reasonable registration fee for the workshop/CME/conference after approval of the first party.",
  "The second party shall arrange to and fro transport of the faculties provided by AMASI and their accommodation and food. The second party can either ask the faculties to book their own transport and re-imburse them at the venue of the workshop/CME/conference or can directly book the airline/train tickets for the faculties as per a mutually suitable itinerary.",
  "However, an exception is made for academic events organized by state chapters of small states to promote academics in such states. In these states, AMASI shall provide the to and fro transport for 2-3 of its faculties. The local hospitality, accomodation and food of these faculties shall still remain the responsibility of the organizers. The states in which these exceptions are made are as under: a) Jammu & Kashmir b) Uttarakhand c) Himachal Pradesh d) Tripura e) Meghalaya f) Manipur g) Nagaland h) Arunachal Pradhesh i) Mizoram j) Sikkim.",
  "The Second party shall not display any audiovisual material at the venue to promote meeting, conferences, workshops of any other professional body without intimating the first party.",
  "The second party shall not utilize the workshop/CME/conference for personal propaganda, promotion of their private hospital, political propaganda or purpose other than academic dissemination of knowledge.",
  "The second party shall bear the full financial responsibility of the event. The first party shall not in any way bear financial liabilities for the workshop/CME/conference. The second party also in not liable to make any payment to the first party for the same.",
  "The Second Party shall forward a detailed program listing all the members of the OC, the schedule of lectures/operations and the faculties involved to the first party at least 3 weeks before the commencement of the event.",
  "The first party will display the event and its schedule including links for registration for the event if provided by the first party on it website. For this, the full details have to be submitted by the second party to the first party at least 3 weeks prior to the event.",
  "If such a facility is available, the first party will send an email circular to its members who have registered their emails with the first party intimating them of the event provided the second party submits such details in appropriate format to the first party at least 3 weeks prior to the event.",
  "The Second Party shall maintain close liaison with the First party. Organizing Secretary shall provide full details of the facilities available for the workshop/CME/conference to Hon. Secretary of AMASI at least 1month in advance. The full responsibility of conducting the workshop/CME/conference will rest with the second party and AMASI will in no way liable or answerable to the delegates.",
  "The Organizing Secretary shall submit a report to Hony. Secretary AMASI after conclusion of the workshop/CME/conference. It should include workshop/CME/conference photographs, The report should reach Hony. Secretary, AMASI within fifteen days.",
  "This Memorandum of Understanding has to be signed by the Organizing Secretary of the workshop/CME/conference on behalf of the Second party. Hony. Secretary of AMASI has to sign on behalf of the First party. If the Organizing Secretary of selected workshop/CME/conference fails to sign the Memorandum of Understanding at least 15 days prior to the event, invitation stands cancelled and Second Party shall not use the logo or name of the first party for any such event.",
]

export const RURAL_PROGRAM_CLAUSES: string[] = [
  "ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA hereinafter called AMASI being the First Party and ORGANISING COMMITTEE OF RURAL SURGICAL CAMP hereafter called OC being the second party, we the first party and the second party hereby enter in MOU as per the following details.",
  "Executive Committee of AMASI (EC) shall be the authority to represent the first party. Honorary Secretary of AMASI shall carry out all instruction of the Executive Committee of AMASI and is the authorized signatory of the first party.",
  "The authorities to present the second party shall be office bearers of Organizing Committee of the rural surgical camp. Organizing Secretary of the rural surgical camp shall act on the advice of the Organizing Committee. He is authorized to sign for the second party. The Organizing Committee is responsible for the proper conduction of the rural surgical camp.",
  "The venue of the rural surgical camp at the place already decided will be at the discretion of the OC, subject to endorsement of EC of AMASI. However, the camp has to be in a hospital located in a rural setting and not in any urban area.",
  "AMASI is holding the full right of authority to sanction any academic activities where the name 'AMASI' and Logo of AMASI will be used in any form either digital, print or both.",
  "A letter seeking such permission must be addressed to Secretary, AMASI HQ before announcing the programme.",
  "All the banners, brochures, print materials, electronic materials associated with the event should bear the logos of both AMASI as well as ASI.",
  "If the second party wishes to hold a program in any guest institution, a letter of consent from Head of the institution must be attached with request letter.",
  "If the second party wishes to hold a program individually in private institution, he / she must attach a brief about the institution.",
  "If the second party proposes to hold any program jointly with other association, a letter of consent form of the partner association must be attached with request letter.",
  "AMASI HQ will complete the official processing of such request latest by two weeks after receiving such request.",
  "There is no option/permission to open of any Bank Account in the name of AMASI in any form in any circumstances for such workshops/CME/conferences.",
  "The Second Party will decide the programme of the Rural surgical camp, only after approval of the first party. The second party shall make arrangements for the conduction of the rural surgical camp. It includes arranging appropriate instruments, disposables, and personnel for assistance. The second party may solicit the support of pharmaceutical companies, surgical goods manufacturers and private individuals for donation in cash or kind for the same.",
  "All the faculties at such rural surgical camp have to be bonafide members of AMASI. Exceptions can be made for faculties belonging to other specialities like anesthetists, gynecologists, urologists, gastroenterologists, etc. after prior intimation to the first party.",
  "The Second Party can fix a reasonable registration fee for the rural surgical camp after approval of the first party.",
  "The second party shall arrange to and fro transport of the faculties provided by AMASI from the nearest railhead or airport and their accommodation and food. The faculties shall reach the nearest railhead/airport at their own expense on request of the first party.",
  "The Second party shall not display any audiovisual material at the venue to promote meeting, conferences, workshops of any other professional body without intimating the first party.",
  "The second party shall not utilize the rural surgical camp for personal propaganda, promotion of their private hospital, political propaganda or purpose other than service to the population.",
  "The second party shall bear the full financial responsibility of the event. The first party shall not in any way bear financial liabilities for the rural surgical camp. The second party also in not liable to make any payment to the first party for the same.",
  "For rural surgical camp, AMASI shall provide financial assistance upto Rs. One lakh only, on receiving the original bills and vouchers.",
  "The Second Party shall forward a detailed program listing all the members of the OC, the schedule of lectures/operations and the faculties involved to the first party at least 3 weeks before the commencement of the event.",
  "The first party will display the event and its schedule including links for registration for the event if provided by the first party on it website. For this, the full details have to be submitted by the second party to the first party at least 3 weeks prior to the event.",
  "The Second Party shall maintain close liaison with the First party. Organizing Secretary shall provide full details of the facilities available for the rural surgical camp to Hon. Secretary of AMASI at least 1month in advance. The full responsibility of conducting the rural surgical camp will rest with the second party and AMASI will in no way liable or answerable to the beneficiaries of such a camp.",
  "The Organizing Secretary shall submit a report to Hony. Secretary AMASI after conclusion of the rural surgical camp. It should include rural surgical camp photographs, the location of the camp, a brief description of the beneficiaries of the camp, the total number of surgeries performed. The report should reach Hony. Secretary, AMASI within fifteen days.",
  "This Memorandum of Understanding has to be signed by the Organizing Secretary of the rural surgical camp on behalf of the Second party. Hony. Secretary of AMASI has to sign on behalf of the First party. If the Organizing Secretary of selected rural surgical camp fails to sign the Memorandum of Understanding at least 15 days prior to the event, invitation stands cancelled and Second Party shall not use the logo or name of the first party for any such event.",
]

// AMASICON MOU — transcribed from
// https://amasi.org/wp-content/uploads/2025/06/MOU-for-AMASICON.pdf (41
// clauses + the "Procedures to be followed" sheet). The "20XX" / blank
// placeholders in the original are kept as-is: the signed application row
// (organizer, date, venue) is printed in the acknowledgment box above the
// clauses, so the clause text itself stays byte-stable for the hash.
export const AMASICON_CLAUSES: string[] = [
  "ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA hereinafter called AMASI being the First Party and ORGANISING COMMITTEE OF AMASI CONFERENCE hereafter called OC being the second party, we the first party and the second party hereby enter in MOU as per the following details.",
  "Executive Committee of AMASI (EC) shall be the authority to represent the first party. Honorary Secretary of AMASI shall carry out all instruction of the Executive Committee of AMASI and is the authorized signatory of the first party.",
  "The authorities to present the second party shall be office bearers of Organizing Committee which invited the conference. Organizing Secretary of the conference shall act on the advice of the Organizing Committee. He is authorized to sign for the second party. The Organizing Committee is responsible for the proper conduction of the conference.",
  "If any official body other than AMASI is also involved in organizing the conference, e.g. the local or state chapter of Association of Surgeons of India (ASI), prior intimation and approval of the first party will need to be taken.",
  "The Annual Conference of AMASI (hereinafter called as AMASICON20XX) shall be held on the agreed dates at the agreed place. The organizing secretary for the same shall be the applicant named in this application, a valid member of AMASI since the year stated in the application.",
  "The venue of the conference at the place already decided will be at the discretion of the OC, subject to endorsement of EC of AMASI.",
  "All the banners, brochures, print materials, electronic materials associated with the event should bear the logos of both AMASI as well as ASI.",
  "The First Party will decide the programme of the Conference. This includes selection of speakers, subjects, timings, allotment of halls, chairman etc. The second party shall make arrangements for the conduction of the conference. It includes providing halls of adequate capacity, audiovisual equipment and management, suitable podium in each hall and personnel for assistance.",
  "The Second Party is bounded by the decision of the General Body of AMASI regarding Registration fees for the conference.",
  "Orator, Guest Speakers from Overseas and India and persons to be admitted as Honorary Fellowship at the conference are exempt from paying Registration fees. Hony. Secretary of AMASI shall send list of these persons (Exemption list) as approved by the EC to the Organizing Secretary. The Second Party shall honour this list. The first party may make any addition to this thereafter. The Second party shall not allow any complimentary registrations or accommodation at the cost of the conference, unless it is by agreement of the First Party.",
  "All the AMASI EC, including the President, Past Presidents and Secretary, are supposed to register for the conference and make their own arrangements for stay and transport to the city of the conference. However, the AMASI EC members are given the privilege that they may register at the lowest rate offered by the Second Party since the announcement of that particular AMASICON. Also the Second Party will provide the EC members with transportation to and from the airport/railway station to their place of accommodation/venue.",
  "The Second party shall provide: (a) Local Hospitality (HOTEL STAY, REGISTRATION AND LOCAL TRANSPORT) to persons on exemption list. (b) Free accommodation and food to office staff of AMASI. Suitable accommodation very near the venue of the Conference is preferable. (c) Computer, Typewriter, Furniture and Stationery to office staff of AMASI. (d) One stall near registration counter to AMASI Office staff for collecting subscription etc. and one room for keeping the valuables of the central office.",
  "The Second Party shall open only one account (and not more than one) in the name of AMASICON (year) at a bank. Hony. Treasurer of OC and two other office bearers (Organizing Secretary or Organizing Chairman) of OC (number to be decided by OC) shall operate the account (Conference A/C). The account shall be operable by at least two signatures of which one should be that of the Treasurer.",
  "Organizing Secretary must print the following: All money paid shall be in the form of crossed account payee demand draft (cheques permitted for local banks) payable to AMASICON (year), account number (a/c no.) of (name of Bank) at (name of city). Cheques/drafts without account number and Bank details shall not be accepted — in first as well as all subsequent circulars including trade circulars to delegates and in all correspondence. (Year) write year of conference e.g. \"AMASICON 2016\"; (A/c no.) write account number e.g. \"Savings 129587\" as per the item above; write name of Bank e.g. \"State Bank of India\"; (City) write name of the city e.g. \"Mumbai\".",
  "All conference collections including Registration fees, advertisement, stall charges, sponsorship etc. must be deposited in conference a/c only.",
  "The Second Party shall issue a receipt on receiving money. The receipt should be sent to the Delegate or person / institution concerned within 7 days of receiving the draft or realization of cheque.",
  "The Second Party shall forward the list of office bearers and Chairman of various committees to Hony. Secretary of AMASI at least one year prior to the conference. The list of members of the Finance committee and name of Office Bearer authorized to operate the conference a/c should also be sent along with it.",
  "Second party may arrange Pre-conference workshop or Post-conference programme. Full management including fees, speakers etc. will be done by the second party. However, its accounts shall be kept under separate head under main conference account. All money transactions shall be from conference a/c only.",
  "Executive Committee and other committee meetings of AMASI will be held on any Day of Conference. The second party shall make proper arrangements for the same.",
  "The first party will appoint scrutinizing committee for scientific paper etc., which will consist of 5-6 members including President and Hon. Secretary.",
  "The first party will provide the deadlines for various activities relating to the holding of AMASICON. The second party will abide by these deadlines.",
  "Printing & dispatch to all members will be done by the Second party.",
  "The Second Party shall maintain close liaison with the First party. Organizing Secretary shall provide full details of the facilities available for the conference to Hon. Secretary of AMASI at least 9 months in advance.",
  "Organizing Secretary, in his circular, shall inform all members: (i) Details regarding accommodation at Hotels, etc. (ii) Weather conditions at the place and consequent clothing requirements etc. (iii) Train timings relevant to the conference. (iv) Flight/air timings relevant to the conference. (v) Sightseeing places with details. (vi) Name, address and other details of Travel agents (if appointed) to cater to accommodation, travel, sightseeing etc. of delegates; accommodation tariff, commission for booking tickets, charges for sightseeing etc.; deposit to be sent in advance to travel agents. OC should supervise the working of the travel agents so that they deal fairly with delegates; the Organizing Secretary should attend any complaints against the travel agents and take proper action. (vii) Registration fees as decided by the General Body of AMASI. (viii) Registration form must include AMASI membership number of the delegate if he claims to be one. The Organizing Secretary must confirm the membership of AMASI before accepting him in the category of AMASI member.",
  "The Second Party will decide about person to be invited to the Conference as Inaugurator after consultation with the President, AMASI. The Organizing Secretary shall also send a small introductory bio-data of the inaugurator; suitable mementoes will be prepared by the Second Party on behalf of AMASI. Protocol of AMASI shall be followed at these functions.",
  "The Second Party shall arrange for the inauguration function, the convocation function of FMAS program and the General body meeting of AMASI as per instructions of the First party. Protocol of AMASI shall be followed at these functions.",
  "The OC may bring out a souvenir on the occasion of the Conference. Suitable advertisements may be accepted at charges fixed by the Committee. The Souvenir will contain photographs of office bearers of AMASI as well as main members of OC and inaugurator. The souvenir shall also contain messages from the chairman and the patron(s) of the conference. In addition, the souvenir should carry the abstracts of all papers and videos (including free paper, award paper, junior scholar paper, free and award videos) with details of the presenting author. Organizing secretary shall send a copy of the circular inviting advertisements in the Souvenir wherein rates of charges are printed to Hony. Secretary AMASI.",
  "The Second Party may call a press conference before Conference wherein salient features of the conference shall be highlighted.",
  "OC may allow stalls to be put up at the Conference venue at rates fixed by it. The Organizing Secretary shall send the following information to Hony. Secretary, AMASI before the Conference begins: (a) Total number of stalls put up, approximate size of each. (b) List of stalls occupied and by whom, mentioning total charges for each stall. (c) Rate of stalls — ordinary and special. (d) Total collection from stalls; in case some companies have not yet paid, the same should be indicated. As per terms in item 13, all collections must be credited to the Conference a/c only.",
  "The OC may accept sponsorship for various events, thus receiving donations in cash or in the form of dinners, lunches etc. As in the case of stalls, details of each sponsorship including the amount collected from each (value in case of dinners, lunches) should be submitted to Hony. Secretary AMASI, before the Conference.",
  "The Second Party shall host dinner for Members of EC, President and Secretary of AMASI, Past Presidents of AMASI and their spouses and special invitees.",
  "Office bearers of OC viz. Chairman, Organizing Secretary, Treasurer & Joint Secretary as well as members of Finance Committee shall be full members of AMASI. OC shall maintain meticulous accounts of the conference. After the conference is over, OC shall clear all liabilities and get the account audited.",
  "Organizing Secretary shall send unaudited provisional account of the Conference to Hony. Secretary AMASI within three months.",
  "AMASI may get the Conference accounts audited by its own auditors or those appointed by it. The Second Party shall supply all information and documents required for the same.",
  "Audited Conference accounts shall be submitted to Hony. Secretary and Hony. Treasurer of AMASI within 06 months for placing before the EC for its approval.",
  "The first party will provide seed money not exceeding Rs. 10 lakh (ten lakhs only) to the second party for the initial funding required as soon as the MOU is signed and conference account opened. The entire seed money has to be returned from the conference account to AMASI account within one month of completion of the conference. The seed money amount may be increased or decreased on mutual agreement of both the First and the Second Parties.",
  "The Second Party shall remit Rs. 05 lakhs or 30% of the Registration fees, whichever is higher, to AMASI headquarters within three months of the conference along with the provisional unaudited accounts. Once the conference account is audited and closed, one of the following three courses shall be adopted: (i) In case the excess of income over expenditure is less than Rs. 20,00,000/- (Rupees Twenty lakhs): The Second Party is liable to pay a minimum guarantee amount of Rs. 20,00,000/- (Rupees twenty lakhs only). Twenty lakhs will be transferred to the AMASI account and will be used for AMASI Headquarters activities (no amount shall be earmarked for the city/state or zonal activities in which the conference was conducted). (ii) In case the excess of income over expenditure is between Rs. 20,00,000/- and Rs. 40,00,000/-: The surplus is to be transferred to the AMASI account, of which Rs. 20,00,000/- will remain with AMASI headquarters and the remaining is to be utilized as follows — if the conference has been hosted in a government teaching hospital, a part of the OC's share may be used for equipment or events contributing to the academics of medical students and resident doctors; the OC's share may be used for academic programs of the respective zonal section of AMASI; the utilization of the OC's share shall be determined by the OC members consisting of Organizing Chairman, Organizing Secretary, Organizing Co-secretary and the Treasurer with the approval of the EC of AMASI as represented by the current Hon. Secretary of AMASI; and the utilization shall be in tranches not exceeding 3 lakhs for a single purpose/event. (iii) In case the excess of income over expenditure is MORE THAN Rs. 40,00,000/-: The surplus is to be transferred to the AMASI account, of which 50% will remain with AMASI headquarters and the remaining 50% is to be utilized on the same terms as in (ii).",
  "A list of delegates with details of the conference shall be sent to the Central Office either by CD or by letter. It is mandatory to computerize conference data and a CD (read only) containing the above information should be sent instead of printed sheets.",
  "If the Second Party fails to make payments as provided in this contract, it will be considered unpaid debt. The First Party will adopt one or more of the penal and disciplinary procedures. A resolution of the Executive Committee to this effect will be conclusive and binding.",
  "The Organizing Secretary shall submit a report to Hony. Secretary AMASI after conclusion of the conference. It should include conference photographs, two copies of video recording of inaugural function (one for office, the other for the President of that year) and two copies of all conference publications. It should also mention the number of surgeries demonstrated in live workshop, the total number of registered delegates, the number of national and international faculties. The report should reach Hony. Secretary, AMASI within one month of the conference.",
  "This Memorandum of Understanding has to be signed by the Organizing Secretary of the conference on behalf of the Second party. Hony. Secretary of AMASI has to sign on behalf of the First party. If the Organizing Secretary of selected conference fails to sign the Memorandum of Understanding at least 12 months prior to the agreed date, the invitation stands cancelled and the General Body shall consider alternate invitations for selection.",
]

export const AMASICON_PROCEDURES: NonNullable<NumberedClauseTemplate["appendix"]> = {
  title: "PROCEDURES TO BE FOLLOWED FOR AMASICON",
  sections: [
    {
      heading: "Pre-incorporation",
      items: [
        "Open a separate bank account in the name of AMASICON.",
        "Enroll in a separate GST registration and comply with the procedures laid down as per the GST rules.",
        "Apply for a separate TAN number (tax deducted at source).",
      ],
    },
    {
      heading: "Post incorporation",
      items: [
        "File the GST returns on a regular basis and maintain proper records such as GST registration certificate, GST returns (GSTR-1, GSTR-3B and GSTR-2B), tax remittance challans.",
        "File the GSTR-9 and GSTR-9C returns (annual return) if applicable.",
        "Deduct TDS and remit the same within the stipulated time and file the quarterly returns in time.",
      ],
    },
    {
      heading: "For finalisation of accounts",
      items: [
        "Maintain proper books of accounts in accounting software (recommended: Tally).",
        "Maintain the proper expense bills and related details including bank statements.",
        "Prepare the reconciliation statement of TDS deducted and paid.",
        "Prepare the reconciliation statement of GST collected and paid.",
        "Prepare the reconciliation statement of TDS on income earned and deducted by others.",
        "Furnish the Profit and Loss account and Balance Sheet along with the audit report.",
      ],
    },
    {
      heading: "End process",
      items: [
        "Hand over all the financial records after completion of the conference.",
        "Surrender the GST registration.",
        "Close the bank account; any funds available are to be transferred to the AMASI Head Office bank account.",
        "Cancel the TAN registration (TDS number).",
      ],
    },
  ],
}

function getNumberedClauseTemplate(typeId: ApplicationTypeId): NumberedClauseTemplate {
  if (typeId === "workshop") {
    return {
      title: "MEMORANDUM OF UNDERSTANDING FOR WORKSHOP/CME/CONFERENCE (OTHER THAN AMASICON)",
      roleLabel: "workshop/CME/conference",
      clauses: WORKSHOP_CLAUSES,
    }
  }
  if (typeId === "amasicon") {
    return {
      title: "MEMORANDUM OF UNDERSTANDING FOR AMASICON",
      roleLabel: "AMASICON, on behalf of the second party",
      clauses: AMASICON_CLAUSES,
      appendix: AMASICON_PROCEDURES,
    }
  }
  return {
    title: "MEMORANDUM OF UNDERSTANDING FOR RURAL SURGERY CAMP",
    roleLabel: "rural surgical camp",
    clauses: RURAL_PROGRAM_CLAUSES,
  }
}

function renderNumberedClauseMou(application: AcademicEventApplication, signature: MouSignature | null) {
  const template = getNumberedClauseTemplate(application.application_type_id)

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.letterheadOrg}>ASSOCIATION OF MINIMAL ACCESS SURGEONS OF INDIA</Text>
        <Text style={styles.letterheadTitle}>{template.title}</Text>
        <Text style={styles.letterheadContact}>
          AMASI Head Office 45 A, Pankaja Mill Rd, Ramanathapuram, Coimbatore, +914224223330 amasi.india@gmail.com
          www.amasi.org
        </Text>

        <Acknowledgment application={application} />

        {template.clauses.map((clause, i) => (
          <View style={styles.clauseRow} key={i}>
            <Text style={styles.clauseNum}>{i + 1}.</Text>
            <Text style={styles.clauseText}>{clause}</Text>
          </View>
        ))}

        {template.appendix && (
          <View break>
            <Text style={styles.docTitle}>{template.appendix.title}</Text>
            {template.appendix.sections.map((section) => (
              <View key={section.heading}>
                <Text style={styles.sectionHeading}>{section.heading}</Text>
                <BulletList items={section.items} />
              </View>
            ))}
          </View>
        )}

        <View style={styles.signatureBlock}>
          <Text style={styles.signatureLine}>Signed: _________________ (Hon Secretary of AMASI)</Text>
          <Text style={styles.signatureLine}>
            Signed: {application.organizer_name} (Organizing Secretary of {template.roleLabel})
          </Text>
          {signature && (
            <>
              <Text style={[styles.signatureLine, { marginTop: 10, fontSize: 8.5, color: "#555" }]}>
                Electronic signature record — {signature.signatory_name} ({signature.signatory_email}), accepted{" "}
                {formatDate(signature.accepted_at)} from IP {signature.ip_address}. Document hash:{" "}
                {signature.mou_sha256.slice(0, 16)}…
              </Text>
              {signature.approved_by && signature.approved_at && (
                <Text style={[styles.signatureLine, { fontSize: 8.5, color: "#555" }]}>
                  Counter-signed by {signature.approved_by} ({formatDate(signature.approved_at)}) on behalf of AMASI.
                </Text>
              )}
            </>
          )}
        </View>

        <Footer application={application} />
      </Page>
    </Document>
  )
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const COLLEGE_OF_MAS_TYPES: ApplicationTypeId[] = ["fmas", "mmas", "dmas"]
const ARTICLE_TYPES: ApplicationTypeId[] = ["slcp", "nextgen", "meet_the_master", "zonal_event"]
const NUMBERED_CLAUSE_TYPES: ApplicationTypeId[] = ["workshop", "rural_program", "amasicon"]

export async function generateMouPdf(
  application: AcademicEventApplication,
  typeLabel: string,
  signature?: MouSignature | null
): Promise<Buffer> {
  let doc: React.ReactElement<DocumentProps>

  if (COLLEGE_OF_MAS_TYPES.includes(application.application_type_id)) {
    doc = renderCollegeOfMasMou(application, typeLabel)
  } else if (ARTICLE_TYPES.includes(application.application_type_id)) {
    doc = renderArticleMou(application)
  } else if (NUMBERED_CLAUSE_TYPES.includes(application.application_type_id)) {
    doc = renderNumberedClauseMou(application, signature ?? null)
  } else {
    throw new Error(`generateMouPdf: unsupported application_type_id "${application.application_type_id}"`)
  }

  return renderToBuffer(doc)
}
